### PR TITLE
Create pookalm.py

### PR DESCRIPTION
**Pull request by Amith1206**

### CODE REVIEW

**Comment by kurianbenoy** [comment]
Add screenshot of pookalam and I will merge it now

**Comment by Amith1206** [comment]
pookalam output

**Comment by Amith1206** [comment]
will that be enough @kurianbenoy

**Comment by kurianbenoy** [comment]
Add screenshot in the folder

**Comment by kurianbenoy** [comment]
Merged for now, create a separate PR with screenshot image in the folder Amith Tony

**Pull request merged**
