### PR TITLE
Final Submission

### PR DESCRIPTION
**Pull request by adithyaanilkumar**
I am a student studying CSE at MEC.
This is my final submission for Code_A_pookalam.
This is done completely using python.
Please merge it as soon as possible.

### CODE REVIEW

**Comment by kurianbenoy** [comment]
Looks great, you have added a screenshot image of Pookalam

**Comment by adithyaanilkumar** [comment]
Thank you for the merge. I didn't quite get what you meant bt screenshot
image? I didn't know any other way to take a picture of the output. Should
i edit anything in the submission?

**Comment by kurianbenoy** [comment]
@adithyaanilkumar add a screenshot of the Pookalam image like this: https://github.com/FossMec/Code-a-pookalam/blob/master/sample_submission/sample.png.

If possible adding the video to this repository is also recommended.

**Comment by adithyaanilkumar** [comment]
I have uploaded the video.please merge it to the master branch.

**Pull request merged**
